GET http://localhost:8000/api/data/

###

GET http://localhost:8000/api/data/60293a84bd16ca36384bfe5c

###

POST http://localhost:8000/api/data/
Content-Type: application/json

{
  "year": 2021,
  "month": "February",
  "total_from_start": 5,
  "brought_forward": 2,
  "new_claims": 3,
  "previous_backlog": 0,
  "reopened_in_month": 3,
  "closed": 1,
  "carried_forward": 0,
  "settled_at_nil": 1,
  "settled_claims": 1 
}